# Generated by Django 4.1.1 on 2022-10-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
