# Generated by Django 4.1.1 on 2022-10-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0002_empleado_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
    ]
