# Generated by Django 4.1.1 on 2022-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0005_categoria_clientes_det_ventas_producto_ventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
